# Generated by Django 4.2.16 on 2024-12-01 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoproducto',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='carritoproducto',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuarios',
        ),
        migrations.RemoveField(
            model_name='pedidoproducto',
            name='pedido_ppid',
        ),
        migrations.RemoveField(
            model_name='pedidoproducto',
            name='producto_ppid',
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_cid', to='categorias.categoria', verbose_name='Categoría'),
        ),
        migrations.DeleteModel(
            name='Carrito_compra',
        ),
        migrations.DeleteModel(
            name='CarritoProducto',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='PedidoProducto',
        ),
    ]
