# Generated by Django 4.2.14 on 2024-10-10 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito_compra',
            fields=[
                ('id_carrito', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('cantidad_total_productos', models.IntegerField()),
                ('monto_carrito', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre_categoria', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_compra', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('metodo_pago', models.CharField(max_length=30)),
                ('monto_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('estado_pedido', models.BooleanField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('tfno', models.CharField(max_length=10)),
                ('contrasena', models.CharField(max_length=10)),
                ('foto', models.ImageField(null=True, upload_to='usuarios/')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('estado_producto', models.BooleanField()),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(max_length=50)),
                ('foto_producto', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('cantidad_producto', models.IntegerField()),
                ('categoria_cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_cid', to='gestion.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto_carrito', models.IntegerField()),
                ('pedido_ppid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.pedido')),
                ('producto_ppid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.producto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(through='gestion.PedidoProducto', to='gestion.producto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario_pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_pid', to='gestion.usuario'),
        ),
        migrations.CreateModel(
            name='CarritoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto_carrito', models.IntegerField()),
                ('carrito_cppid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.carrito_compra')),
                ('producto_cppid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.producto')),
            ],
        ),
        migrations.AddField(
            model_name='carrito_compra',
            name='productos',
            field=models.ManyToManyField(through='gestion.CarritoProducto', to='gestion.producto'),
        ),
    ]
