# Generated by Django 5.1.2 on 2024-10-11 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(default=' - ', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.BooleanField(verbose_name='Envíado(?)'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_compra',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Id de la compra'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(max_length=30, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='monto_pedido',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad pedida'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario_pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_pid', to='gestion.usuario', verbose_name='Id del usuario'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad_producto',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria_cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_cid', to='gestion.categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=50, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado_producto',
            field=models.BooleanField(verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto_producto',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Foto del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Id del producto'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(max_length=10, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(null=True, upload_to='usuarios/', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tfno',
            field=models.CharField(max_length=10, verbose_name='Teléfono'),
        ),
    ]
