# Generated by Django 4.2.14 on 2024-10-12 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_rename_usuario_pid_pedido_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='monto_pedido',
        ),
    ]
