# Generated by Django 5.1.1 on 2024-11-29 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_remove_pedido_monto_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoproducto',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='carritoproducto',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuarios',
        ),
        migrations.RemoveField(
            model_name='pedidoproducto',
            name='pedido_ppid',
        ),
        migrations.RemoveField(
            model_name='pedidoproducto',
            name='producto_ppid',
        ),
        migrations.DeleteModel(
            name='Carrito_compra',
        ),
        migrations.DeleteModel(
            name='CarritoProducto',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='PedidoProducto',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
